# using v1.25.2-jammy because it's the only version which has
#   python3.10, and is latest version
FROM mcr.microsoft.com/playwright/python:v1.25.2-jammy

RUN pip install pipenv

CMD [ "--base-url", "http://localhost:1313" ]
ENTRYPOINT [ "pytest" ]

COPY test/Pipfile test/Pipfile.lock ./
# installing depenencies to the container's system,
#   so we don't have to worry about venvs
RUN pipenv --bare sync --system
