name: Development
description: For issues encountered with our development environment.
labels:
  - "dev"
body:
  - type: markdown
    attributes:
      value: |
        #### Please be as specific as possible. Thank you for your help supporting this project!
        ### Please check to see if someone else has already reported this bug.
  - type: input
    attributes:
      label: Tools
      description: What tool(s) are affected?
      placeholder: Docker, GH Actions, Make, etc.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the issue you encountered. Feel free to throw in screenshots and/or screencasts if helpful (they always are!)
    validations:
      required: true
