name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run hugo server
        uses: jakejarvis/hugo-build-action@master 
        with:
          args: serve -D --bind 0.0.0.0
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: test