name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run hugo build
        uses: jakejarvis/hugo-build-action@master 
        with:
          args: --gc --config ./config.toml
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: start static file server
        uses: Eun/http-server-action@v1
        with:
          directory: ./public
          port: 1313
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: test